[package]
name = "tree-sitter-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.41"
serde = "1.0.219"
serde_json = "1.0.140"
tree-sitter = "0.25.8"
tree-sitter-java = "0.23.5"
tree-sitter-python = "0.23.6"
tree-sitter-rust = "0.24.0"
tree-sitter-sequel = "0.3.8"
