name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: tree-sitter-tools
        path: target/release/tree-sitter-tools
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install musl
      run: |
        # 安装依赖
        rustup default stable
        rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release --verbose
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: tree-sitter-tools
        path: target/release/tree-sitter-tools
